-- Leads desde Passline (SOLO resultados de buscador, nunca se visita passline.com: ver docs/runbooks/passline-leads.md).
-- Idempotente. Solo crea/modifica objetos public.aitickets_* (proyecto Supabase compartido).
-- RLS activado SIN políticas + REVOKE ALL a anon/authenticated (tablas, secuencias y funciones) => solo la service role.

-- 1. Eventos vistos en una ticketera de la competencia (una fila por URL de evento).
CREATE TABLE IF NOT EXISTS public.aitickets_competitor_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  platform text NOT NULL DEFAULT 'passline',
  url text NOT NULL UNIQUE,
  title text,
  venue text,
  city text,
  region text,
  event_date date,
  category text,
  producer_name text,
  -- Id numérico del productor en la ticketera (solo del archivo semilla passline_rm.json).
  producer_ref text,
  snippet text,
  -- 'search' (resultado de buscador) | 'seed' (archivo local importado a mano).
  seen_via text NOT NULL DEFAULT 'search',
  lead_id uuid REFERENCES public.aitickets_leads(id) ON DELETE SET NULL,
  first_seen_at timestamptz NOT NULL DEFAULT now(),
  last_seen_at timestamptz NOT NULL DEFAULT now(),
  times_seen int NOT NULL DEFAULT 1
);
CREATE INDEX IF NOT EXISTS aitickets_competitor_events_lead_idx
  ON public.aitickets_competitor_events (lead_id) WHERE lead_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS aitickets_competitor_events_platform_seen_idx
  ON public.aitickets_competitor_events (platform, last_seen_at DESC);
CREATE INDEX IF NOT EXISTS aitickets_competitor_events_event_date_idx
  ON public.aitickets_competitor_events (event_date);
CREATE INDEX IF NOT EXISTS aitickets_competitor_events_producer_idx
  ON public.aitickets_competitor_events (lower(producer_name)) WHERE producer_name IS NOT NULL;
ALTER TABLE public.aitickets_competitor_events ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.aitickets_competitor_events FROM PUBLIC, anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.aitickets_competitor_events TO service_role;
REVOKE ALL ON SEQUENCE public.aitickets_competitor_events_id_seq FROM PUBLIC, anon, authenticated;
GRANT USAGE, SELECT ON SEQUENCE public.aitickets_competitor_events_id_seq TO service_role;

-- 2. Columnas nuevas en leads (seguimiento manual desde Gmail + datos de Passline).
ALTER TABLE public.aitickets_leads ADD COLUMN IF NOT EXISTS lead_type text;
ALTER TABLE public.aitickets_leads ADD COLUMN IF NOT EXISTS name_key text;
ALTER TABLE public.aitickets_leads ADD COLUMN IF NOT EXISTS instagram text;
ALTER TABLE public.aitickets_leads ADD COLUMN IF NOT EXISTS whatsapp text;
-- [{field, value, url, found_at}]: de dónde salió cada dato de contacto (registro de origen).
ALTER TABLE public.aitickets_leads ADD COLUMN IF NOT EXISTS contact_sources jsonb NOT NULL DEFAULT '[]'::jsonb;
ALTER TABLE public.aitickets_leads ADD COLUMN IF NOT EXISTS events_on_passline int NOT NULL DEFAULT 0;
ALTER TABLE public.aitickets_leads ADD COLUMN IF NOT EXISTS last_seen_event_at timestamptz;
-- {title, date, url, venue}
ALTER TABLE public.aitickets_leads ADD COLUMN IF NOT EXISTS last_passline_event jsonb;
ALTER TABLE public.aitickets_leads ADD COLUMN IF NOT EXISTS contacts_enriched_at timestamptz;
ALTER TABLE public.aitickets_leads ADD COLUMN IF NOT EXISTS notes text;
-- true = el dueño lo contacta a mano (Gmail): el outreach automático nunca lo enriquece ni lo pone en secuencia.
ALTER TABLE public.aitickets_leads ADD COLUMN IF NOT EXISTS manual_only boolean NOT NULL DEFAULT false;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'aitickets_leads_lead_type_check') THEN
    ALTER TABLE public.aitickets_leads
      ADD CONSTRAINT aitickets_leads_lead_type_check CHECK (lead_type IS NULL OR lead_type IN ('producer', 'venue'));
  END IF;
END
$$;

-- Dedupe de leads de Passline: 'producer:<nombre normalizado>' o 'venue:<nombre>|<ciudad>' (lo calcula la app).
CREATE UNIQUE INDEX IF NOT EXISTS aitickets_leads_name_key_uidx ON public.aitickets_leads (name_key);
CREATE INDEX IF NOT EXISTS aitickets_leads_source_idx ON public.aitickets_leads (source, status);

-- 3. Fuente registrada (la corrida la controla LEADS_PASSLINE_ENABLED; enabled=false en esta fila la apaga también).
INSERT INTO public.aitickets_lead_sources (key, enabled) VALUES ('passline_search', true)
ON CONFLICT (key) DO NOTHING;

-- 4. Upsert atómico de eventos vistos: inserta o actualiza (times_seen + 1, last_seen_at = now()).
--    Nunca borra datos ya conocidos (coalesce con lo existente primero para producer_name/venue/city).
--    p_rows: [{url, platform?, title?, venue?, city?, region?, event_date?, category?, producer_name?, producer_ref?, snippet?}]
CREATE OR REPLACE FUNCTION public.aitickets_touch_competitor_events(p_rows jsonb, p_seen_via text DEFAULT 'search')
RETURNS TABLE (id bigint, url text, lead_id uuid, inserted boolean)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
#variable_conflict use_column
BEGIN
  IF jsonb_typeof(p_rows) IS DISTINCT FROM 'array' THEN
    RAISE EXCEPTION 'aitickets_touch_competitor_events: p_rows debe ser un arreglo';
  END IF;
  IF jsonb_array_length(p_rows) > 500 THEN
    RAISE EXCEPTION 'aitickets_touch_competitor_events: máximo 500 filas por llamada';
  END IF;
  RETURN QUERY
  INSERT INTO public.aitickets_competitor_events AS t
    (platform, url, title, venue, city, region, event_date, category, producer_name, producer_ref, snippet, seen_via)
  SELECT DISTINCT ON (r->>'url')
    coalesce(nullif(r->>'platform', ''), 'passline'),
    r->>'url',
    left(nullif(r->>'title', ''), 300),
    left(nullif(r->>'venue', ''), 200),
    left(nullif(r->>'city', ''), 100),
    left(nullif(r->>'region', ''), 100),
    CASE WHEN r->>'event_date' ~ '^\d{4}-\d{2}-\d{2}$' THEN (r->>'event_date')::date END,
    left(nullif(r->>'category', ''), 50),
    left(nullif(r->>'producer_name', ''), 200),
    left(nullif(r->>'producer_ref', ''), 50),
    left(nullif(r->>'snippet', ''), 1000),
    coalesce(nullif(p_seen_via, ''), 'search')
  FROM jsonb_array_elements(p_rows) AS r
  WHERE coalesce(r->>'url', '') <> ''
  ON CONFLICT ON CONSTRAINT aitickets_competitor_events_url_key DO UPDATE SET
    title = coalesce(EXCLUDED.title, t.title),
    venue = coalesce(t.venue, EXCLUDED.venue),
    city = coalesce(t.city, EXCLUDED.city),
    region = coalesce(t.region, EXCLUDED.region),
    event_date = coalesce(EXCLUDED.event_date, t.event_date),
    category = coalesce(t.category, EXCLUDED.category),
    producer_name = coalesce(t.producer_name, EXCLUDED.producer_name),
    producer_ref = coalesce(t.producer_ref, EXCLUDED.producer_ref),
    snippet = coalesce(EXCLUDED.snippet, t.snippet),
    seen_via = CASE WHEN EXCLUDED.seen_via = 'search' THEN 'search' ELSE t.seen_via END,
    last_seen_at = now(),
    times_seen = t.times_seen + 1
  RETURNING t.id, t.url, t.lead_id, (t.xmax = 0) AS inserted;
END;
$$;
REVOKE EXECUTE ON FUNCTION public.aitickets_touch_competitor_events(jsonb, text) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.aitickets_touch_competitor_events(jsonb, text) TO service_role;

-- 5. El lote de envíos automáticos nunca toma leads de seguimiento manual (defensa adicional al filtro de la app).
CREATE OR REPLACE FUNCTION public.aitickets_claim_outreach_batch(p_limit int)
RETURNS SETOF public.aitickets_leads
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  RETURN QUERY
  WITH due AS (
    SELECT l.id
    FROM public.aitickets_leads l
    WHERE l.status IN ('enriched', 'contacted')
      AND l.email IS NOT NULL
      AND NOT l.manual_only
      AND l.next_action_at IS NOT NULL
      AND l.next_action_at <= now()
    ORDER BY l.sequence_step ASC, l.score DESC NULLS LAST, l.next_action_at ASC
    LIMIT greatest(0, least(coalesce(p_limit, 0), 100))
    FOR UPDATE SKIP LOCKED
  )
  UPDATE public.aitickets_leads t
     SET next_action_at = now() + interval '30 minutes',
         updated_at = now()
    FROM due
   WHERE t.id = due.id
  RETURNING t.*;
END;
$$;
REVOKE EXECUTE ON FUNCTION public.aitickets_claim_outreach_batch(int) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.aitickets_claim_outreach_batch(int) TO service_role;
