-- Enlaces de acceso directo (recuperar / cambiar contraseña): registro de uso único.
-- Idempotente. Solo crea public.aitickets_auth_link_tokens (proyecto Supabase compartido).
--
-- El enlace es un token firmado por AI Tickets (src/lib/magic-link.ts, HMAC con EMAIL_VERIFY_SECRET)
-- con {uid, purpose, exp, jti}. Al usarlo, /auth/link inserta su jti aquí: si ya existe, el enlace ya
-- se usó y se rechaza. Las filas vencidas se pueden borrar (el código limpia las de más de 1 día).
-- RLS activado SIN políticas + REVOKE ALL a anon/authenticated => solo la service role.

CREATE TABLE IF NOT EXISTS public.aitickets_auth_link_tokens (
  jti text PRIMARY KEY,
  auth_user_id uuid NOT NULL,
  purpose text NOT NULL CHECK (purpose IN ('recovery', 'change-password', 'login')),
  expires_at timestamptz NOT NULL,
  used_at timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE public.aitickets_auth_link_tokens ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.aitickets_auth_link_tokens FROM PUBLIC, anon, authenticated;

CREATE INDEX IF NOT EXISTS aitickets_auth_link_tokens_expires_idx
  ON public.aitickets_auth_link_tokens (expires_at);

-- Envíos de enlaces de acceso: límite DURABLE por cuenta (el límite en memoria de cada instancia
-- serverless no basta). /api/auth/magic-link inserta una fila por intento; solo se envía si no hubo
-- otro envío de la misma cuenta en los últimos 60 s y hay menos de 3 en la última hora. Los intentos
-- rechazados borran su fila. Mismo esquema de acceso: solo service role.
CREATE TABLE IF NOT EXISTS public.aitickets_auth_link_sends (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  auth_user_id uuid NOT NULL,
  purpose text NOT NULL CHECK (purpose IN ('recovery', 'change-password', 'login')),
  sent_at timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE public.aitickets_auth_link_sends ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.aitickets_auth_link_sends FROM PUBLIC, anon, authenticated;

CREATE INDEX IF NOT EXISTS aitickets_auth_link_sends_user_idx
  ON public.aitickets_auth_link_sends (auth_user_id, sent_at DESC);
